import React from "react";

const useTrnFormMeter = () => {
	const formSectionsTrnMeter = {
		goodReceiving: {
			metaData: 1,
			customerAdr: 0,
			billing: 0,
			customer: 0,
			assetData: 1,
			asr: 1,
			actionTaken: 0,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		returnToSupplier: {
			metaData: 1,
			customerAdr: 0,
			billing: 0,
			customer: 0,
			assetData: 1,
			asr: 1,
			actionTaken: 0,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		installation: {
			metaData: 1,
			customerAdr: 1,
			billing: 1,
			customer: 1,
			assetData: 1,
			asr: 0,
			actionTaken: 1,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		commissioning: {
			metaData: 1,
			customerAdr: 0,
			billing: 0,
			customer: 0,
			assetData: 1,
			asr: 0,
			actionTaken: 0,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		vending: {
			metaData: 1,
			customerAdr: 0,
			billing: 0,
			customer: 1,
			assetData: 1,
			asr: 0,
			actionTaken: 0,
			vending: 1,
			commissioning: 0,
			decomissioning: 0,
		},
		missing: {
			metaData: 1,
			customerAdr: 0,
			billing: 0,
			customer: 0,
			assetData: 1,
			asr: 0,
			actionTaken: 0,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		found: {
			metaData: 1,
			customerAdr: 0,
			billing: 0,
			customer: 0,
			assetData: 1,
			asr: 0,
			actionTaken: 1,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		disconnection: {
			metaData: 1,
			customerAdr: 1,
			billing: 0,
			customer: 1,
			assetData: 1,
			asr: 0,
			actionTaken: 1,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		reconnection: {
			metaData: 1,
			customerAdr: 1,
			billing: 0,
			customer: 1,
			assetData: 1,
			asr: 0,
			actionTaken: 1,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		audit: {
			metaData: 1,
			customerAdr: 1,
			billing: 1,
			customer: 1,
			assetData: 1,
			asr: 0,
			actionTaken: 1,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		inspection: {
			metaData: 1,
			customerAdr: 1,
			billing: 1,
			customer: 1,
			assetData: 1,
			asr: 0,
			actionTaken: 1,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
		sell: {
			metaData: 1,
			customerAdr: 0,
			billing: 0,
			customer: 0,
			assetData: 1,
			asr: 0,
			actionTaken: 0,
			vending: 0,
			commissioning: 0,
			decomissioning: 0,
		},
	};

	return { formSectionsTrnMeter };
};

export default useTrnFormMeter;
